[platformio]
lib_dir = lib

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<mega/>
    -<uno/>
lib_extra_dirs = lib

build_flags =
    -std=gnu++17
    -Ilib/RZlibrairiesPersoNew/src
    -Ilib/RZlibrairiesPersoNew/src/actuators
    -Ilib/RZlibrairiesPersoNew/src/communication
    -Ilib/RZlibrairiesPersoNew/src/config
    -Ilib/RZlibrairiesPersoNew/src/control
    -Ilib/RZlibrairiesPersoNew/src/hardware
    -Ilib/RZlibrairiesPersoNew/src/navigation
    -Ilib/RZlibrairiesPersoNew/src/safety
    -Ilib/RZlibrairiesPersoNew/src/sensors
    -Ilib/RZlibrairiesPersoNew/src/system

lib_deps = 
    adafruit/Adafruit NeoPixel@^1.15.2
    arduino-libraries/Arduino_LSM6DS3@^1.0.3
    bogde/HX711@^0.7.5
    teckel12/NewPing@^1.9.7
    paulstoffregen/Encoder@1.4.4

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<uno/>
    -<mega/>
lib_extra_dirs = lib

build_flags =
    -std=gnu++17
    -Ilib/RZlibrairiesPersoNew/src
    -Ilib/RZlibrairiesPersoNew/src/actuators
    -Ilib/RZlibrairiesPersoNew/src/communication
    -Ilib/RZlibrairiesPersoNew/src/config
    -Ilib/RZlibrairiesPersoNew/src/control
    -Ilib/RZlibrairiesPersoNew/src/hardware
    -Ilib/RZlibrairiesPersoNew/src/navigation
    -Ilib/RZlibrairiesPersoNew/src/safety
    -Ilib/RZlibrairiesPersoNew/src/sensors
    -Ilib/RZlibrairiesPersoNew/src/system

lib_deps = 
    pololu/DualVNH5019MotorShield@^3.0.0
