[platformio]
; Chemin vers le dossier lib partagé (optionnel)
lib_dir = ../../arduino/lib
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
framework = arduino
board = megaatmega2560
monitor_speed = 115200
build_flags = -std=gnu++17
; Ajouter si vous connaissez le port COM
; upload_port = COM3
lib_deps = 
	pololu/DualVNH5019MotorShield@^3.0.0
	adafruit/Adafruit NeoPixel@^1.15.2
	arduino-libraries/Arduino_LSM6DS3@^1.0.3
	bogde/HX711@^0.7.5
	teckel12/NewPing@^1.9.7
	paulstoffregen/Encoder@1.4.4
